# -*- coding: utf-8 -*-
#
# Red Pitaya documentation build configuration file, created by
# sphinx-quickstart on Fri Sep 16 12:27:19 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import datetime
#import sphinx_rtd_theme     # import theme

# ReadTheDocs environment detection
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

sys.path.append(os.path.abspath('.') + '/_extensions')
sys.path.append(os.path.abspath('.')+ '/_links')
sys.path.append(os.path.abspath('.'))

# Import external links configuration
from _links.link import EXTERNAL_LINKS, SPHINX_EXTLINKS

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '6.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_rtd_theme',
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.todo',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.extlinks',  # For external link shortcuts
    'sphinx_tabs.tabs',
    'sphinx_copybutton',  # For better code copying
    'notfound.extension',
    'github',
    'myst_parser'
]

# MyST Parser configuration
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

# External Links configuration
extlinks = SPHINX_EXTLINKS

# Sphinx copybutton configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True

# Global RST substitutions (added to every RST file)
rst_epilog = """
.. Common external links - these can be used in any RST file as |link_name|

.. |redpitaya| replace:: `Red Pitaya <https://redpitaya.com/>`__
.. |redpitaya-github| replace:: `Red Pitaya GitHub <https://github.com/RedPitaya/>`__
.. |redpitaya-forum| replace:: `Red Pitaya Forum <https://forum.redpitaya.com/>`__
.. |redpitaya-store| replace:: `Red Pitaya Store <https://redpitaya.com/shop/>`__
.. |sphinx-docs| replace:: `Sphinx Documentation <https://www.sphinx-doc.org/>`__
.. |python| replace:: `Python <https://www.python.org/>`__
.. |numpy| replace:: `NumPy <https://numpy.org/>`__
.. |matplotlib| replace:: `Matplotlib <https://matplotlib.org/>`__
.. |xilinx| replace:: `Xilinx <https://www.xilinx.com/>`__
.. |vivado| replace:: `Vivado <https://www.xilinx.com/products/design-tools/vivado.html>`__
.. |scpi| replace:: `SCPI <https://www.ivifoundation.org/scpi/>`__
.. |br| raw:: html

   <br/>

"""

sphinx_tabs_valid_builders = ['linkcheck']

sphinx_tabs_disable_tab_closing = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown'
    }

# The encoding of source files.
source_encoding = 'utf-8-sig'       # default value "utf-8-sig"


# The master toctree document.
root_doc = 'index'


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'README.md']

# Warns about all references not being found
nitpicky = True



# General information about the project.
project = "Red Pitaya"
html_title = "Red Pitaya Documentation"
project_copyright = f"{datetime.date.today().year}, Red Pitaya d.o.o"
copyright = project_copyright  # Sphinx requires this variable name
author = "Red Pitaya"

# The version info for the project you're documenting, acts as a replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "2.05-37"
# The full version, including alpha/beta/rc tags.
release = version

# The language for content is autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'



# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Performance optimizations
html_scaled_image_link = False
html_copy_source = True
html_show_sourcelink = False

# Build performance
numfig = True
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': 'Section %s',
}

# Suppress warnings for known issues
suppress_warnings = [
    'image.nonlocal_uri',
    'ref.ref',
]


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of built-in themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {'body_max_width':'70%'}
html_theme_options = {
    'logo_only': True,
    'collapse_navigation': False,
    'navigation_depth': 5,
    'includehidden': True,
    'titles_only': False,
    'sticky_navigation': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'vcs_pageview_mode': '',
    # Analytics
    'analytics_id': '',  # Add your Google Analytics ID here if needed
    'analytics_anonymize_ip': False,
}

# Not needed (latest sphinx) Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar. The default is the same as html_title.
#html_short_title = None


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "img/redpitaya-logo.svg"

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "img/favicon.png"

# SEO and metadata
html_meta = {
    'description': 'Official Red Pitaya technical documentation',
    'keywords': 'Red Pitaya, FPGA, oscilloscope, signal generator, documentation',
    'author': 'Red Pitaya d.o.o',
    'viewport': 'width=device-width, initial-scale=1.0',
}

# Social media cards
# Note: display_version option removed as it's deprecated in newer sphinx_rtd_theme versions



html_css_files = [
    'page_width.css',
    'tabs.css',
    'new_style.css'
]

# For compatibility with older Sphinx versions
html_context = {
        'css_files': [
            'https://media.readthedocs.org/css/sphinx_rtd_theme.css',
            'https://media.readthedocs.org/css/readthedocs-doc-embed.css',
            '_static/page_width.css',
            '_static/tabs.css',
            '_static/new_style.css'
        ],
    }

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'RedPitayaDocs'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',

# Latex figure (float) alignment
#'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (root_doc, 'RedPitaya-Documentation.tex', html_title, author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = "img/head_logo.png"

# For "manual" documents, if this is true, then top-level headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# It false, will not define \strong, \code, 	itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#latex_keep_old_macro_names = True

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (root_doc, 'RedPitaya-Documetantion', html_title, author, 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (root_doc, 'RedPitaya-Documentation', html_title, author, 'RedPitaya',
    'Red Pitaya Techincal Documentation', 'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


intersphinx_mapping = {
    'knowledgebase': ('https://redpitaya-knowledge-base.readthedocs.io/en/latest/', None),
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# We recommend adding the following config value.
# Sphinx defaults to automatically resolve *unresolved* labels using all your Intersphinx mappings.
# This behaviour has unintended side-effects, namely that documentation local references can
# suddenly resolve to an external location.
# See also:
# https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_disabled_reftypes
intersphinx_disabled_reftypes = ["*"]

# ReadTheDocs specific configuration
if on_rtd:
    # On ReadTheDocs, we don't need to specify the theme path
    html_theme_path = []
    # Use the RTD theme's built-in version dropdown
    html_theme_options.update({
        'canonical_url': 'https://redpitaya.readthedocs.io/',
        'analytics_id': '',  # Add your analytics ID if you have one
        'analytics_anonymize_ip': False,
        'logo_only': True,
        # 'display_version': True,  # Removed - deprecated in newer sphinx_rtd_theme versions
        'prev_next_buttons_location': 'bottom',
        'style_external_links': False,
        'vcs_pageview_mode': '',
        'style_nav_header_background': 'white',
        'collapse_navigation': False,
        'sticky_navigation': True,
        'navigation_depth': 4,
        'includehidden': True,
        'titles_only': False
    })
else:
    # Local development settings
    html_theme_options.update({
        'collapse_navigation': False,
    })
