
Here are some other ways to update the ecosystem and Red Pitaya Linux OS:

* :ref:`Software update manager <software_update_manager>` - accessible from the main web interface. Can only update the ecosystem version.
* :ref:`Manually update the SD card <prepareSD>` - can be used to update the Red Pitaya Linux OS and ecosystem. For updating between major releases this is the recommended method.
* :ref:`Updater command line tool <update_util>` - can be used to automatically update the **nightly build** ecosystem version.
* :ref:`OS update chapter <os_update>` - describes all possiblities for updating the Red Pitaya OS and ecosystem.