Tutorial ideas:

- Description of the base v0.94 project and its components.
- Add a general build for FPGA (use Anton Potocnik as a basis)
- Add inclusion of a custom module to the existing v0.94 build (magisterska)
- Add conversion from one board model to another (e.g. from STEMLab 125-14 to SIGNALlab 250-12)
- Add new FPGA lessons:
    - Binary counter
    - Simple PWM generator (GPIOs)
    - FIR filter
    - Generation of a sine wave
    - Output modulation
    - Connecting existing components (adding a new signal)