
Red Pitaya boards can be powered through the +5V pin (pin 1) of the |E2| connector.

**External Power Specifications:**

+--------------------------+-----------------------------+
| **Parameter**            | **Specification**           |
+==========================+=============================+
| Power supply voltage     | 5 V                         |
+--------------------------+-----------------------------+
| Maximum current          | 3.0 A                       |
+--------------------------+-----------------------------+
| Power supply type        | DC                          |
+--------------------------+-----------------------------+
| Abs. max. voltage        | 5.5 V                       |
+--------------------------+-----------------------------+
| Abs. min. voltage        | 4.5 V                       |
+--------------------------+-----------------------------+

The +5V pin features a 3.0 A PTC resettable fuse for overcurrent protection. The fuse is located on the PCB near the extension connector |E2|.

**Available Power Rails on Extension Connectors:**

+--------------------------+-----------------------------+
| **Voltage Rail**         | **Current Limit**           |
+==========================+=============================+
| +5 V                     | 0.5 A [#f13]_               |
+--------------------------+-----------------------------+
| -5 V                     | 0.1 A                       |
+--------------------------+-----------------------------+
| +3V3                     | 0.5 A [#f13]_               |
+--------------------------+-----------------------------+
